# Generated by Django 6.0.6 on 2026-06-20 12:36

import django.db.models.deletion
import studio.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngleJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_image_url', models.TextField()),
                ('horizontal_angle', models.FloatField(default=0.0)),
                ('vertical_angle', models.FloatField(default=0.0)),
                ('zoom', models.FloatField(default=5.0)),
                ('additional_prompt', models.TextField(blank=True)),
                ('num_images', models.PositiveSmallIntegerField(default=1)),
                ('seed', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canvas Angle Job',
                'verbose_name_plural': 'Canvas Angle Jobs',
                'db_table': 'canvas_angle_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.ImageField(upload_to=studio.models.library_upload_to)),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canvas Scene',
                'verbose_name_plural': 'Canvas Scenes',
                'db_table': 'canvas_scenes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AngleResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='studio.anglejob')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_angle_results', to='studio.dataasset')),
            ],
            options={
                'verbose_name': 'Canvas Angle Result',
                'verbose_name_plural': 'Canvas Angle Results',
                'db_table': 'canvas_angle_results',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='studio.datafolder')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.AddField(
            model_name='dataasset',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='studio.datafolder'),
        ),
        migrations.CreateModel(
            name='ImageEditJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('size', models.CharField(blank=True, default='1024x1024', max_length=32)),
                ('resolution', models.CharField(choices=[('2K', '2K'), ('4K', '4K')], default='2K', max_length=4)),
                ('num_images', models.PositiveSmallIntegerField(default=1)),
                ('is_cutout', models.BooleanField(default=False)),
                ('source_image', models.ImageField(blank=True, null=True, upload_to=studio.models.canvas_edit_upload_to)),
                ('source_images', models.JSONField(blank=True, default=list)),
                ('intermediate_image', models.ImageField(blank=True, null=True, upload_to=studio.models.canvas_edit_intermediate_upload_to)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('split_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studio.imageeditjob')),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_edit_jobs', to='studio.scene')),
            ],
            options={
                'verbose_name': 'Canvas Image Edit Job',
                'verbose_name_plural': 'Canvas Image Edit Jobs',
                'db_table': 'canvas_image_edit_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageEditResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_image_edit_results', to='studio.dataasset')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='studio.imageeditjob')),
            ],
            options={
                'verbose_name': 'Canvas Image Edit Result',
                'verbose_name_plural': 'Canvas Image Edit Results',
                'db_table': 'canvas_image_edit_results',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='anglejob',
            name='scene',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angle_jobs', to='studio.scene'),
        ),
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('duration', models.PositiveSmallIntegerField(default=10)),
                ('aspect_ratio', models.CharField(default='16:9', max_length=16)),
                ('task_id', models.CharField(blank=True, max_length=128)),
                ('result_url', models.TextField(blank=True)),
                ('thumbnail_url', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_jobs', to='studio.scene')),
            ],
            options={
                'verbose_name': 'Canvas Video Job',
                'verbose_name_plural': 'Canvas Video Jobs',
                'db_table': 'canvas_video_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dataasset',
            unique_together={('folder', 'filename')},
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='studio.scene')),
            ],
            options={
                'verbose_name': 'Canvas Chat Message',
                'verbose_name_plural': 'Canvas Chat Messages',
                'db_table': 'canvas_chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['scene', 'created_at'], name='canvas_chat_scene_ts_idx')],
            },
        ),
    ]
