# Generated by Django 6.0.6 on 2026-06-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageeditjob',
            name='resolution',
            field=models.CharField(choices=[('1K', '1K'), ('2K', '2K'), ('4K', '4K')], default='2K', max_length=4),
        ),
    ]
