# Generated by Django 6.0.6 on 2026-07-16 11:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_alter_imageeditjob_resolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='robots', to='studio.scene')),
            ],
            options={
                'verbose_name': 'Canvas Robot',
                'verbose_name_plural': 'Canvas Robots',
                'db_table': 'canvas_robots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RobotRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], db_index=True, default='QUEUED', max_length=16)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('robot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='studio.robot')),
            ],
            options={
                'verbose_name': 'Canvas Robot Run',
                'verbose_name_plural': 'Canvas Robot Runs',
                'db_table': 'canvas_robot_runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
