# Generated by Django 6.0.6 on 2026-07-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0003_robot_robotrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='allow_writes',
            field=models.BooleanField(default=False),
        ),
    ]
