# Generated by Django 6.0.8 on 2026-08-07 08:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_delete_robot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=200)),
                ('overrides', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canvas Image Model',
                'verbose_name_plural': 'Canvas Image Models',
                'db_table': 'canvas_image_models',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ImageProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=500)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('defaults', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canvas Image Provider',
                'verbose_name_plural': 'Canvas Image Providers',
                'db_table': 'canvas_image_providers',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='imageeditjob',
            name='image_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studio.imagemodel'),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='studio.imageprovider'),
        ),
    ]
