# Generated by Django 6.0.8 on 2026-08-14 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0008_import_image_env'),
    ]

    operations = [
        migrations.AddField(
            model_name='anglejob',
            name='image_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='studio.imagemodel'),
        ),
        migrations.AddField(
            model_name='imageprovider',
            name='kind',
            field=models.CharField(choices=[('image', 'Image generation'), ('angle', 'Camera angle re-render')], db_index=True, default='image', max_length=16),
        ),
    ]
