# Generated by Django 6.0.8 on 2026-08-17 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0011_imageprovider_base_url_charfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='image_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_jobs', to='studio.imagemodel'),
        ),
        migrations.AlterField(
            model_name='imageprovider',
            name='kind',
            field=models.CharField(choices=[('image', 'Image generation'), ('angle', 'Camera angle re-render'), ('video', 'Video generation')], db_index=True, default='image', max_length=16),
        ),
    ]
