# Generated by Django 6.0.8 on 2026-08-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0013_import_video_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageprovider',
            name='kind',
            field=models.CharField(choices=[('image', 'Image generation'), ('angle', 'Camera angle re-render'), ('video', 'Video generation'), ('chat', 'Chat agent LLM')], db_index=True, default='image', max_length=16),
        ),
    ]
