# Generated by Django 6.0.8 on 2026-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_imageprovider_base_url_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprovider',
            name='request_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='imageprovider',
            name='kind',
            field=models.CharField(choices=[('image', 'Image generation'), ('angle', 'Camera angle re-render'), ('video', 'Video generation'), ('chat', 'Chat agent LLM'), ('custom_image', 'Custom image generation (request template)'), ('custom_video', 'Custom video generation (request template)')], db_index=True, default='image', max_length=16),
        ),
    ]
