# Generated by Django 6.0.8 on 2026-08-21 16:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0016_imageprovider_base_url_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('source', models.CharField(choices=[('builtin', 'Built-in'), ('user', 'User-installed')], db_index=True, default='user', max_length=16)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Canvas Skill',
                'verbose_name_plural': 'Canvas Skills',
                'db_table': 'canvas_skills',
                'ordering': ['name'],
            },
        ),
    ]
