# Generated by Django 6.0.8 on 2026-08-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0019_merge_0017_custom_channel_0018_import_builtin_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageprovider',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageprovider',
            name='last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='imageprovider',
            name='last_status',
            field=models.CharField(blank=True, choices=[('ok', 'Last call succeeded'), ('error', 'Last call failed')], default='', max_length=8),
        ),
    ]
