# Generated by Django 6.0.8 on 2026-08-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0020_channel_health'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='resolution',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
