# Generated by Django 6.0.8 on 2026-09-04 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0025_video_no_ratio_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageeditjob',
            name='resolution',
            field=models.CharField(blank=True, default='2K', max_length=16),
        ),
    ]
